CREATE TABLE account (
    id INT PRIMARY KEY IDENTITY(1,1),
    userName NVARCHAR(100) NOT NULL UNIQUE,
    password NVARCHAR(100) NOT NULL,
    phone NVARCHAR(15) NOT NULL UNIQUE,
    firstName NVARCHAR(20) NOT NULL,
    lastName NVARCHAR(20) NOT NULL,
    avatar NVARCHAR(255),
    status NVARCHAR(255) NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL
);

GO
    CREATE NONCLUSTERED INDEX idx_id ON account(id);
GO
    CREATE NONCLUSTERED INDEX idx_userName ON account(userName);
GO
    CREATE NONCLUSTERED INDEX idx_phone ON account(phone);
GO

CREATE TABLE [statistic] (
    id INT PRIMARY KEY IDENTITY(1,1),
    myRank INT NOT NULL,
    allOrder INT NOT NULL,
    allMoney FLOAT(53) NOT NULL,
    preMonthOrder INT NOT NULL,
    thisMonthOrder INT NOT NULL,
	preMonthMoney FLOAT(53) NOT NULL,
    thisMonthMoney FLOAT(53) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    CONSTRAINT FK_statistics_Users FOREIGN KEY (userId) REFERENCES account(id)
);
GO

CREATE TABLE contact (
    id INT PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(100) NOT NULL UNIQUE,
    phone NVARCHAR(15) NOT NULL UNIQUE,
    address NVARCHAR(100) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    CONSTRAINT FK_contact_Users FOREIGN KEY (userId) REFERENCES account(id)
);
GO

CREATE TABLE [role] (
    id INT PRIMARY KEY IDENTITY(1,1),
    [role] NVARCHAR(255) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    CONSTRAINT FK_role_Users FOREIGN KEY (userId) REFERENCES account(id)
);
GO