CREATE TABLE [product] (
    id INT PRIMARY KEY IDENTITY(1,1),
	title NVARCHAR(255) NOT NULL,
	image NVARCHAR(255) NOT NULL,
    name NVARCHAR(255) NOT NULL,
    size NVARCHAR(255) NOT NULL,
    amount NVARCHAR(255) NOT NULL,
	sold NVARCHAR(255) NOT NULL,
	discount NVARCHAR(255) NOT NULL,
	fishCodeInProduct NVARCHAR(255) NOT NULL,
    price NVARCHAR(255) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    userId INT NOT NULL,
	fishCodeId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),

	CONSTRAINT FK_product_Users FOREIGN KEY (userId) REFERENCES account(id),
    CONSTRAINT FK_product_FishCodes FOREIGN KEY (fishCodeId) REFERENCES fishCode(id)
);
GO