CREATE TABLE fishCode (
    id INT PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(255) NOT NULL,
    size NVARCHAR(255) NOT NULL,
    amount NVARCHAR(255) NOT NULL,
    price NVARCHAR(255) NOT NULL,
	detail NVARCHAR(MAX) NOT NULL,
    status NVARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    updateTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    createTime DATETIMEOFFSET(7) NOT NULL DEFAULT SYSDATETIMEOFFSET(),

    CONSTRAINT FK_fishCode_Users FOREIGN KEY (userId) REFERENCES account(id)
);
GO